[versions]
# Core libraries
jsoup = "1.21.2"
pdfbox = "2.0.30"
openhtmltopdf = "1.0.10"
kotlinx-html = "0.11.0"
mustache = "0.9.10"
thymeleaf = "3.1.2.RELEASE"
freemarker = "2.3.33"
groovy = "3.0.22"
pebble = "3.2.4"
jasper = "6.16.0"
arrow = "2.1.2"

# ZwojeIJPlugin libraries
gson = "2.10.1"
pdf-renderer = "1.0.5"
swinky = "0.0.24"

# Kotlin and testing
kotest = "6.0.4"
kluent = "1.73"
mockk = "1.13.8"
coroutines-test = "1.7.3"

[libraries]
# --- Core ---
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
pdfbox = { module = "org.apache.pdfbox:pdfbox", version.ref = "pdfbox" }
openhtmltopdf-core = { module = "com.openhtmltopdf:openhtmltopdf-core", version.ref = "openhtmltopdf" }
openhtmltopdf-pdfbox = { module = "com.openhtmltopdf:openhtmltopdf-pdfbox", version.ref = "openhtmltopdf" }
kotlinx-html = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version.ref = "kotlinx-html" }
mustache = { module = "com.github.spullara.mustache.java:compiler", version.ref = "mustache" }
thymeleaf = { module = "org.thymeleaf:thymeleaf", version.ref = "thymeleaf" }
freemarker = { module = "org.freemarker:freemarker", version.ref = "freemarker" }
groovy-templates = { module = "org.codehaus.groovy:groovy-templates", version.ref = "groovy" }
pebble = { module = "io.pebbletemplates:pebble", version.ref = "pebble" }
jasper = { module = "net.sf.jasperreports:jasperreports", version.ref = "jasper" }
arrow-core-jvm = { module = "io.arrow-kt:arrow-core-jvm", version.ref = "arrow" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines-test" }

# --- ZwojeIJPlugin ---
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
pdf-renderer = { module = "org.swinglabs:pdf-renderer", version.ref = "pdf-renderer" }
swinky = { module = "ca.weblite:swinky-main", version.ref = "swinky" }

# --- Test ---
kotest-engine = { module = "io.kotest:kotest-framework-engine-jvm", version.ref = "kotest" }
kluent = { module = "org.amshove.kluent:kluent", version.ref = "kluent" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines-test" }

[plugins]
kotest = { id = "io.kotest", version.ref = "kotest" }